[project]
name = "llama-stack-provider-trustyai-garak"
version = "0.1.0"
description = "OOT provider for garak redteam"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-stack>=0.2.15",
    "fastapi",
    "opentelemetry-api",
    "opentelemetry-exporter-otlp",
    "aiosqlite",
    "greenlet",
    "uvicorn",
    "ipykernel",
    "httpx[http2]",
    "garak==0.12.0",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "black", "isort"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_paths = ["src"]
addopts = "-v"