[project]
name = "llama-stack-provider-trustyai-garak"
version = "0.0.1"
description = "OOT remote provider for garak redteam"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-stack",
    "fastapi",
    "opentelemetry-api",
    "opentelemetry-exporter-otlp",
    "aiosqlite",
    "greenlet",
    "uvicorn",
    "ipykernel",
    "garak",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "black", "isort"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_paths = ["src"]
addopts = "-v"